name: CD to Dev EC2

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Artifact (optional)
        run: echo "Download build artifact if uploaded in CI pipeline"

      - name: Copy JAR to EC2 and Restart App
        env:
          EC2_HOST: ${{ secrets.DEV_EC2_HOST }}
          EC2_USER: ${{ secrets.DEV_EC2_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.DEV_EC2_SSH_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          scp -o StrictHostKeyChecking=no -i private_key.pem target/*.jar $EC2_USER@$EC2_HOST:/home/$EC2_USER/app.jar

          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << EOF
            pkill -f 'java -jar' || true
            nohup java -jar /home/$EC2_USER/app.jar > app.log 2>&1 &
          EOF
